language: cpp

before_install: # clang needs newer boost
 - if [[ ${CXX} = clang++ ]]; then
     sudo add-apt-repository -y ppa:boost-latest/ppa;
     sudo apt-get update;
     sudo apt-get install libboost1.55-all-dev;
   else
     sudo apt-get install libboost-all-dev;
   fi
 - sudo apt-get install openmpi-bin

script:
  - mkdir build && cd build && 
    cmake -DBUILD_TESTING=ON .. && make -j4 &&
    make test ARGS="-V" &&
    sudo make install

compiler:
  - clang
  - gcc
